movie/urls.py
from django.urls import path
from movie import views

app_name = "movie"
urlpatterns = [
    path('', views.index, name="index-movie"),
    path('create/', views.create, name="create-movie"),
    path('edit/<int:movie_id>', views.edit, name="edit-movie"),
    #path('update/<int:movie_id>', views.update, name="update-movie"),
    #path('delete/<int:movie_id>', views.delete, name="delete-movie"),
]

movie_proj/urls.py
from django.contrib import admin
from django.urls import path, include
from .import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),
    path('master', views.master),
    path('movie/', include('movie.urls')),
    #path('movie/', views.movie),
]

movie/models.py
from django.db import models


# Create your models here.
class Movie(models.Model):
    actor = models.CharField(max_length=30)
    movie_title = models.CharField(max_length=50)
    genre = models.CharField(max_length=20)
    release_date = models.CharField(max_length=10)
    imdb = models.CharField(max_length=10)

    def __str__(self):
        return self.movie_title


class Song(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=50)
    song_title = models.CharField(max_length=100)

movie/forms.py
from django import forms
from .import models
class CreateMovie(forms.ModelForm):
    class Meta:
        model = models.Movie
        fields = ['actor', 'movie_title', 'genre', 'release_date', 'imdb']

movie/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Movie
from .forms import CreateMovie
def index(request):
    movies = Movie.objects.all().order_by('movie_title', 'actor', 'genre', 'release_date', 'imdb')
    return render(request,'movie/index.html', {'movies': movies})

def create(request):
    form = CreateMovie()
    if request.method == 'POST':
        form = CreateMovie(request.POST)
        if form.is_valid():
            form.save()
            return redirect('movie.index-branch')
        else:
            form = form.CreateMovie()
    return render(request, 'movie/create.html', {'form': form})
def edit(request, movie_id):
    movie = Movie.objects.get(id=movie_id)
    return render(request, 'movie/edit.html', {'movie': movie})

def update(request, movie_id):
    branch = Movie.objects.get(id=movie_id)
    form = form.CreateMovie(request.POST, instance=Movie)
    if form.is_valid():
        form.save()
        return redirect('movie:index-movie')
    return render(request, 'movie/edit.html', {'movie':Movie})
def delete(request, movie_id):
    movie = Movie.objects.get(id=movie_id)
    movie.delete()
    return redirect('movie:index-movie')

movie_proj/views.py
from django.shortcuts import render
from movie.models import Movie


#Create your views here.

def index(request):
    moviesData = Movie.objects.all()
    data = {
        'moviesData': moviesData
    }
    # for m in moviesData:
    #     print(m.movie_title)
    return render(request, 'index.html', data)

def master(request):
    return render(request, 'master.html')
    

movie/templates/movie/create.html
{% extends 'master.html' %}

{% block content %}
    <form class="site-form" action="" method="POST">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-success">
            save
        </button>
    </form>
{% endblock %}

movie/templates/movie/edit.html
{% extends 'master.html' %}
{% block content %}
    <form method = "POST" class="post-form"
          action="{% url 'movie:edit-movie' movie.id %}">
          {% csrf_token %}
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">
                Movie Id:
            </label>
            <input type="text" name="id" id="id" class="form-control" required maxlength="20" value="{{ movie.id }}"/>
        </div>
    </form>

{% endblock %}

movie/templates/movie/index.html
{% extends 'master.html' %}
{% block content %}

    <div class="row">
        <div class="col-md-3">
            <h1>This is First and it is movie page code</h1>
            <a class="btn btn-primary"
               href="{% url 'movie:create-movie' %}">
                create
            </a>
            <table class="table-hover">
                <tr>
                    <th>No.</th>
                    <th>Actor</th>
                    <th>Title</th>
                    <th>Genre</th>
                    <th>Release Date</th>
                    <th>IMDB Rating</th>
                </tr>
                {% for movie in movies %}
                <tr>
                    <td>{{ movie.id }}</td>
                    <td>{{ movie.actor }}</td>
                    <td>{{ movie.movie_title }}</td>
                    <td>{{ movie.genre }}</td>
                    <td>{{ movie.release_date }}</td>
                    <td>{{ movie.imdb }}</td>
                    <td><a href="{% url 'movie:edit-movie' %}">
                        Edit
                    </a>
                    </td>
                    <td><a href="#">Delete</a></td>

                </tr>
                {% endfor %}
            </table>
        </div>
    </div>

{% endblock %}

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Movie WatchList</title>
    <style>
        table, th, td {
            border: 1px solid white;
            border-collapse: collapse;
        }
        th, td {
        background-color: #96D4D4;
        }
        .container
        {
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="item-container">
           <table>
                <ul>
                    <th>Movie Title</th>
                    <th>Genre</th>
                    <th>Actor</th>
                    <th>Release Date</th>
                    <th>IMDB</th>
                </ul>
                <ol>
                    {% for d in moviesData %}
                    <tr>
                        <td>{{d.movie_title}}</td>
                        <td>{{d.genre}}</td>
                        <td>{{d.actor}}</td>
                        <td>{{d.release_date}}</td>
                        <td>{{d.imdb}}</td>
                    </tr>
                    {% endfor%}
                </ol>
           </table>
        </div>
    </div>
    
</body>
</html>

templates/master.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>PROJECT</title>
</head>
<body>
<!--navigation codes-->
    {% block content %}
    {% endblock %}
    <!--footer-->
    
</body>
</html>